const wantRemove = {
  hairStyle: [
    "Hair Style",
    "Long Hair",
    "Short Hair",
    "Ponytail",
    "Braided Hair",
    "Twin Tails",
    "Bangs",
    "Messy Hair",
    "Bob Cut",
    "Curly Hair",
    "Hair Between Eyes",
    "Hime Cut",
    "Side Bangs",
    "Fringe",
    "Pixie Cut",
    "Mohawk",
    "Undercut",
    "Bald",
    "Ombre Hair",
    "ponytail",
    "braid",
    "single braid",
    "very short hair",
    "short hair",
    "medium hair",
    "long hair",
    "very long hair",
    "absurdly long hair",
    "big hair",
    "bald",
    "bald girl",
    // Hairstyles
    "bob cut",
    "inverted bob",
    "bowl cut",
    "buzz cut",
    "chonmage",
    "crew cut",
    "flattop",
    "okappa",
    "pixie cut",
    "undercut",
    // Medium hair
    "flipped hair",
    "wolf cut",
    "animal ears",
    "elf",
    "animal ear fluff",
    "bat ears",
    "bear ears",
    "rabbit ears",
    "cat ears",
    "cow ears",
    "deer ears",
    "dog ears",
    "ferret ears",
    "fox ears",
    "goat ears",
    "horse ears",
    "kemonomimi mode",
    "lion ears",
    "monkey ears",
    "mouse ears",
    "panda ears",
    "pikachu ears",
    "pig ears",
    "raccoon ears",
    "sheep ears",
    "squirrel ears",
    "tiger ears",
    "wolf ears",
    "fake animal ears",
    "animal ear headphones",
    "bear ear headphones",
    "cat ear headphones",
    "rabbit ear headphones",
    "floppy ears",
    "hair ears",
    "other ears",
    "pointy ears",
    "long pointy ears",
    "robot ears",
    "number of ears",
    "extra ears",
    "flat chest",
    "small breasts",
    "medium breasts",
    "large breasts",
    "huge breasts",
    "gigantic breasts",
    "biceps",
    "muscular",
    "toned",
    "abs",
    // horns
    "horned headwear",
    "horned helmet",
    "horned hood",
    "horned mask",
    "black horns",
    "blue horns",
    "brown horns",
    "purple horns",
    "red horns",
    "white horns",
    "single horn",
    "multiple horns",
    "asymmetrical horns",
    "mismatched horns",
    "uneven horns",
    "broken horns",
    "broken horn",
    "cone horns",
    "cow horns",
    "curled horns",
    "demon horns",
    "dragon horns",
    "fake horns",
    "fiery horns",
    "glowing horns",
    "giraffe horns",
    "goat horns",
    "gradient horns",
    "hair horns",
    "huge horns",
    "low horns",
    "mechanical horns",
    "sheep horns",
    "tree horns",
    "skin-covered horns",
    "horn bow",
    "horn ornament",
    "horn ribbon",
    "horn ring",

    // Long hair
    "hime cut",
    "mullet",
    "orange hair",
    // Tied hair
    "bow-shaped hair",
    "shuangyaji",
    "braid",
    "braided bangs",
    "front braid",
    "side braid",
    "french braid",
    "cornrows",
    "crown braid",
    "dreadlocks",
    "single braid",
    "multiple braids",
    "twin braids",
    "low twin braids",
    "tri braids",
    "quad braids",
    "flower-shaped hair",
    "hair bun",
    "braided bun",
    "single hair bun",
    "double bun",
    "cone hair bun",
    "doughnut hair bun",
    "heart hair bun",
    "triple bun",
    "hair rings",
    "feixianji",
    "katsuyamamage",
    "single hair ring",
    "half updo",
    "half up braid",
    "half up half down braid",
    "one side up",
    "two side up",
    "low-braided long hair",
    "low-tied long hair",
    "mizura",
    "multi-tied hair",
    "nihongami",
    "ponytail",
    "folded ponytail",
    "front ponytail",
    "high ponytail",
    "short ponytail",
    "side ponytail",
    "split ponytail",
    "star-shaped hair",
    "topknot",
    "twintails",
    "low twintails",
    "short twintails",
    "uneven twintails",
    "tri tails",
    "quad tails",
    "quin tails",
    "twisted hair",
    // Tall hair
    "afro",
    "huge afro",
    "beehive hairdo",
    "crested hair",
    "liangbatou",
    "pompadour",
    "quiff",
    "shouten pegasus mix mori",
    // Hair texture
    "curly hair",
    "drill hair",
    "twin drills",
    "tri drills",
    "hair flaps",
    "messy hair",
    "pointy hair",
    "ringlets",
    "spiked hair",
    "straight hair",
    "wavy hair",
    // Front of the head
    "bangs",
    "arched bangs",
    "asymmetrical bangs",
    "bangs pinned back",
    "blunt bangs",
    "braided bangs",
    "crossed bangs",
    "choppy bangs",
    "diagonal bangs",
    "dyed bangs",
    "fanged bangs",
    "hair over eyes",
    "hair over one eye",
    "long bangs",
    "parted bangs",
    "curtained hair",
    "wispy bangs",
    "short bangs",
    "swept bangs",
    "hair between eyes",
    "hair intakes",
    "single hair intake",
    "sidelocks",
    "asymmetrical sidelocks",
    "drill sidelocks",
    "low-tied sidelocks",
    "sidelocks tied back",
    "single sidelock",
    "widow's peak",
    // Top of the head
    "ahoge",
    "heart ahoge",
    "huge ahoge",
    "antenna hair",
    "heart antenna hair",
    "comb over",
    "hair pulled back",
    "hair slicked back",
    "mohawk",
    "oseledets",
    // Back of the head
    "lone nape hair",
    // Head hair over the body
    "hair bikini",
    "hair censor",
    "hair in own mouth",
    "hair over breasts",
    "hair over one breast",
    "hair over crotch",
    "hair over shoulder",
    "hair scarf",
    // Misc
    "alternate hairstyle",
    "hair down",
    "hair up",
    "asymmetrical hair",
    "sidecut",
    "blunt ends",
  ],
  hairColor: [
    "hair color",
    "grey hair",
    "blonde hair",
    "black hair",
    "brown hair",
    "red hair",
    "blue hair",
    "green hair",
    "purple hair",
    "pink hair",
    "white hair",
    "silver hair",
    "gray hair",
    "multicolored hair",
    "two tone hair",
    "ombre hair",
    "two-tone hair",
    "streaked hair",
    "dyed hair",
    "pastel hair",
    "rainbow hair",
    "gradient hair",
    "neon hair",
    "metallic hair",
    "vibrant hair",
    "very short hair",
    "short hair",
    "medium hair",
    "long hair",
    "very long hair",
    "absurdly long hair",
    "big hair",
    "bald",
    "bald girl",
    // Hairstyles
    "bob cut",
    "inverted bob",
    "bowl cut",
    "buzz cut",
    "chonmage",
    "crew cut",
    "flattop",
    "okappa",
    "pixie cut",
    "undercut",
    // Medium hair
    "flipped hair",
    "wolf cut",
    // Long hair
    "hime cut",
    "mullet",
    // Tied hair
    "bow-shaped hair",
    "shuangyaji",
    "braid",
    "braided bangs",
    "front braid",
    "side braid",
    "french braid",
    "cornrows",
    "crown braid",
    "dreadlocks",
    "single braid",
    "multiple braids",
    "twin braids",
    "low twin braids",
    "tri braids",
    "quad braids",
    "flower-shaped hair",
    "hair bun",
    "braided bun",
    "single hair bun",
    "double bun",
    "cone hair bun",
    "doughnut hair bun",
    "heart hair bun",
    "triple bun",
    "hair rings",
    "feixianji",
    "katsuyamamage",
    "single hair ring",
    "half updo",
    "half up braid",
    "half up half down braid",
    "one side up",
    "two side up",
    "low-braided long hair",
    "low-tied long hair",
    "mizura",
    "multi-tied hair",
    "nihongami",
    "ponytail",
    "folded ponytail",
    "front ponytail",
    "high ponytail",
    "short ponytail",
    "side ponytail",
    "split ponytail",
    "star-shaped hair",
    "topknot",
    "twintails",
    "low twintails",
    "short twintails",
    "uneven twintails",
    "tri tails",
    "quad tails",
    "quin tails",
    "twisted hair",
    // Tall hair
    "afro",
    "huge afro",
    "beehive hairdo",
    "crested hair",
    "liangbatou",
    "pompadour",
    "quiff",
    "shouten pegasus mix mori",
    // Hair texture
    "curly hair",
    "drill hair",
    "twin drills",
    "tri drills",
    "hair flaps",
    "messy hair",
    "pointy hair",
    "ringlets",
    "spiked hair",
    "straight hair",
    "wavy hair",
    // Front of the head
    "bangs",
    "arched bangs",
    "asymmetrical bangs",
    "bangs pinned back",
    "blunt bangs",
    "braided bangs",
    "crossed bangs",
    "choppy bangs",
    "diagonal bangs",
    "dyed bangs",
    "fanged bangs",
    "hair over eyes",
    "hair over one eye",
    "long bangs",
    "parted bangs",
    "curtained hair",
    "wispy bangs",
    "short bangs",
    "swept bangs",
    "hair between eyes",
    "hair intakes",
    "single hair intake",
    "sidelocks",
    "asymmetrical sidelocks",
    "drill sidelocks",
    "low-tied sidelocks",
    "sidelocks tied back",
    "single sidelock",
    "widow's peak",
    // Top of the head
    "ahoge",
    "heart ahoge",
    "huge ahoge",
    "antenna hair",
    "heart antenna hair",
    "comb over",
    "hair pulled back",
    "hair slicked back",
    "mohawk",
    "oseledets",
    // Back of the head
    "lone nape hair",
    // Head hair over the body
    "hair bikini",
    "hair censor",
    "hair in own mouth",
    "hair over breasts",
    "hair over one breast",
    "hair over crotch",
    "hair over shoulder",
    "hair scarf",
    // Misc
    "alternate hairstyle",
    "hair down",
    "hair up",
    "asymmetrical hair",
    "sidecut",
    "blunt ends",
  ],

  eyesColor: [
    "Black Eyes",
    "Blue Eyes",
    "Brown Eyes",
    "Gray Eyes",
    "Green Eyes",
    "Orange Eyes",
    "Pink Eyes",
    "Purple Eyes",
    "Red Eyes",
    "White Eyes",
    "Yellow Eyes",
    "aqua eyes",
    "black eyes",
    "blue eyes",
    "brown eyes",
    "green eyes",
    "grey eyes",
    "orange eyes",
    "purple eyes",
    "pink eyes",
    "red eyes",
    "white eyes",
    "yellow eyes",
    "amber eyes",
    // Multiple colors of the iris
    "heterochromia",
    "multicolored eyes",
  ],
  backgrounds:[
    "aqua background",
    "beige background", // deprecated
    "black background",
    "blue background",
    "brown background",
    "green background",
    "grey background",
    "light brown background",
    "orange background",
    "pink background",
    "purple background",
    "red background",
    "tan background", // deprecated
    "white background",
    "yellow background",
    "multiple colors",
    "gradient background",
    "greyscale with colored background",
    "monochrome background",
    "multicolored background",
    "rainbow background",
    "heaven condition",
    "two-tone background",
    "argyle background",
    "checkered background",
    "cross background",
    "dotted background",
    "food-themed background",
    "grid background",
    "halftone background",
    "honeycomb background",
    "marble background",
    "paw print background",
    "plaid background",
    "polka dot background",
    "simple background",
    "snowflake background",
    "spiral background",
    "strawberry background",
    "striped background",
    "sunburst background",
    "AI-generated background",
    "abstract background",
    "animal background",
    "text background",
    "backlighting",
    "blending",
    "blurry background",
    "card background",
    "chibi inset",
    "drama layer",
    "fiery background",
    "flag background",
    "floral background",
    "fruit background",
    "game screenshot background",
    "heart background",
    "imageboard colors",
    "lace background",
    "mosaic background",
    "paneled background",
    "photo background",
    "projected inset",
    "Sofmap background",
    "sparkle background",
    "starry background",
    "transparent background",
    "zoom layer"
  ],
  tails: [
    "Main",
    "Tail",
    "Number of tails",
    "Multiple tails",
    "No tail",
    "Types of tail",
    "Supernatural or fictional tails",
    "Demon tail",
    "Dragon tail",
    "Ghost tail",
    "Pikachu tail",
    "Snake head tail",
    "Elemental tails",
    "Fiery tail",
    "Tails of mammals",
    "Bear tail",
    "Rabbit tail",
    "Cat tail",
    "Cow tail",
    "Deer tail",
    "Dog tail",
    "Ermine tail",
    "Fox tail",
    "Horse tail",
    "Leopard tail",
    "Lion tail",
    "Monkey tail",
    "Mouse tail",
    "Pig tail",
    "Sheep tail",
    "Squirrel tail",
    "Tiger tail",
    "Wolf tail",
    "Tails of other animals",
    "Crocodilian tail",
    "Fish tail",
    "Scorpion tail",
    "Snake tail",
    "Tadpole tail",
    "Tails and objects",
    "Tail bell",
    "Tail bow",
    "Tail ornament",
    "Tail piercing",
    "Tail ribbon",
    "Tail ring",
    "Tails and sex",
    "Anal tail",
    "Butt plug tail",
    "Penis tail",
    "Tailjob",
    "Tail masturbation",
    "Tail rape",
    "Misc",
    "Biting another's tail",
    "Mutual tail biting",
    "Biting own tail",
    "Fake tail",
    "Heart tail",
    "Heart tail duo",
    "Holding another's tail",
    "Holding own tail",
    "Holding with tail",
    "Intertwined tails",
    "Panties around tail",
    "Prehensile tail",
    "Spiked tail",
    "Stiff tail",
    "Tail between legs",
    "Tail censor",
    "Tail grab",
    "Tail fondling",
    "Tail pull",
    "Tail raised",
    "Tail stand",
    "Tail wagging",
    "Tail wrap",
    "Things related to the word 'tail' by etymology",
    "Cat o' nine tails",
    "Tailcoat",
    "Whale tail"
], 
eyewearTags: [
  "bespectacled", // for characters who don't normally wear glasses
  "coke-bottle glasses",
  "eyewear on head",
  "eyewear view",
  "eyewear strap",
  "groucho glasses",
  "glass lens",
  "glasses case",
  "jimiko",
  "lensless glasses",
  "looking for glasses",
  "looking over eyewear",
  "nose pads",
  "opaque glasses",
  "rimless eyewear",
  "semi-rimless eyewear",
  "unworn eyewear",
  "eyewear hang",
  "glasses",
  "goggles",
  "monocle",
  "sunglasses",
  "Eyewear",
  
  // Frame colors
  "aqua-framed eyewear",
  "black-framed eyewear",
  "blue-framed eyewear",
  "brown-framed eyewear",
  "green-framed eyewear",
  "grey-framed eyewear",
  "orange-framed eyewear",
  "pink-framed eyewear",
  "purple-framed eyewear",
  "red-framed eyewear",
  "white-framed eyewear",
  "two-tone eyewear",
  "yellow-framed eyewear",

  // Lens colors
  "aqua-tinted eyewear",
  "blue-tinted eyewear",
  "brown-tinted eyewear",
  "gradient-tinted eyewear",
  "green-tinted eyewear",
  "grey-tinted eyewear",
  "multicolor-tinted eyewear",
  "rainbow-tinted eyewear",
  "orange-tinted eyewear",
  "pink-tinted eyewear",
  "purple-tinted eyewear",
  "red-tinted eyewear",
  "yellow-tinted eyewear",

  // Types
  "animal-themed eyewear",
  "cat eye-framed eyewear",
  "food-themed eyewear",
  "heart-shaped eyewear",
  "rectangular eyewear",
  "rimless eyewear",
  "round eyewear",
  "semi-circular eyewear",
  "semi-rimless eyewear",
  "over-rim eyewear",
  "under-rim eyewear",
  "teardrop-framed glasses",
  "triangular eyewear",
  "tortoiseshell-framed eyewear",

  // Actions
  "alternate eyewear",
  "adjusting eyewear",
  "bespectacled",
  "cleaning glasses",
  "crooked eyewear",
  "cum on eyewear",
  "eyewear on head",
  "eyewear on headwear",
  "eyewear strap",
  "eyewear switch",
  "eyewear view",
  "fogged glasses",
  "hand on eyewear",
  "looking over eyewear",
  "no eyewear",
  "removing eyewear",
  "unworn eyewear",
  "eyewear hang",
  "eyewear in mouth",
  "holding removed eyewear",
  "looking for glasses",

  // Accessories
  "eyewear strap",
  "glasses case",
  "nose pads",
  
  // Glasses Types
  "3D glasses",
  "aviator glasses",
  "coke-bottle glasses",
  "diving mask",
  "novelty glasses",
  "heart-shaped eyewear",
  "star-shaped eyewear",
  "teardrop-framed glasses",
  "flight goggles",
  "groucho glasses",
  "lorgnette",
  "opaque glasses",
  "opera glasses",
  "pince-nez",
  "safety glasses",
  "scouter",
  "ski goggles",
  "X-ray glasses",

  // Sunglasses
  "aviator sunglasses",
  "Kamina shades",
  "shutter shades",
  "Simon shades",
  "deal with it (meme) (pixelated glasses)",
  
  // See also
]


  
};
document.addEventListener("DOMContentLoaded", function () {
  document
    .getElementById("retrieveTextBtn")
    .addEventListener("click", function () {
      var textareaContent = document.getElementById(
        "exampleFormControlTextarea1"
      ).value;

      var newStr = textareaContent.replace(/\d+\?/g, ",");
      var finalStr = newStr.replace(/ ?(\? ?)|\? /g, "");
      var finalStr = finalStr.replace(/\b\d+\b/g, "");

      // Lấy tất cả các thẻ có class "tag"
      const tags = document.querySelectorAll(".tags-container .tag");
      // Tạo một mảng để lưu giá trị của các thẻ
      const tagValues = [];

      // Lặp qua từng thẻ và lấy giá trị từ thuộc tính "data-value"
      tags.forEach(function (tag) {
        tagValues.push(tag.getAttribute("data-value"));
      });

      const textAreaValueWantRemove =
        document.getElementById("texteraWantRemove").value;

      // Chuyển đổi giá trị từ textarea thành mảng

      // let element = document.getElementById("texteraout");
      let string = finalStr;
      for (let i = 0; i < tagValues.length; i++) {
        // console.log(tagValues[i]);
        string = removeTags(string, wantRemove, tagValues[i]);
        document.getElementById("out").style.visibility = "visible";
        document.getElementById("texteraout").textContent = "";
        document.getElementById("texteraout").textContent = string;
      }
      let textAreaArray = textAreaValueWantRemove
        .split(" , ")
        .map((item) => item.trim().replace(/,/g, ""))
        .filter((item) => item.length > 0);
      if (textAreaArray.length > 0) {
        if (textAreaArray.some((item) => string.includes(item))) {
          // Nếu chuỗi string chứa ít nhất một phần tử thuộc textAreaArray
          // Xóa các phần tử thuộc textAreaArray khỏi chuỗi string
          textAreaArray.forEach((item) => {
            string = string.replace(item, "");
          });
          let cleanedString = string
            .split(/,\s*/)
            .filter((item) => item.trim() !== "")
            .join(", ");
          document.getElementById("out").style.visibility = "visible";
          document.getElementById("texteraout").textContent = "";
          document.getElementById("texteraout").textContent = cleanedString;
        } else {
          console.log("Chuỗi không chứa phần tử thuộc textAreaArray");
        }
      }

      document.getElementById("out").style.visibility = "visible";
      document.getElementById("texteraout").textContent = "";
      document.getElementById("texteraout").textContent = string;
    });
});

document.addEventListener("DOMContentLoaded", function () {
  var textarea = document.getElementById("exampleFormControlTextarea1");
  textarea.addEventListener("input", function () {
    this.style.height = "auto";
    this.style.height = this.scrollHeight + "px";
  });
});
document.getElementById("tag-select").addEventListener("change", function () {
  const selectedValue = this.value;
  toggleTag(selectedValue);
});

function toggleTag(value) {
  const selectedTagsContainer = document.getElementById("selected-tags");
  const existingTag = document.querySelector(`.tag[data-value="${value}"]`);

  if (existingTag) {
    // Nếu tag đã tồn tại, xóa tag đó
    existingTag.remove();
  } else {
    // Nếu tag chưa tồn tại, thêm tag mới
    const tagDiv = document.createElement("div");
    tagDiv.className = "tag";
    tagDiv.setAttribute("data-value", value);
    tagDiv.innerHTML = `${value} <button class="remove-tag" onclick="removeTag('${value}')">x</button>`;

    selectedTagsContainer.appendChild(tagDiv);
  }
}

function removeTag(value) {
  const tagToRemove = document.querySelector(`.tag[data-value="${value}"]`);
  if (tagToRemove) {
    tagToRemove.remove();
  }
}

function removeTags(text, wantRemove, key) {
  const tags = wantRemove[key];
  const regex = new RegExp(tags.join("|"), "gi");
  const withoutTags = text.replace(regex, "").replace(/\s\s+/g, " ").trim();

  return withoutTags.replace(/,\s*,/g, ","); // Loại bỏ dấu phẩy cuối cùng (nếu có)
}

document
  .getElementById("warningButton")
  .addEventListener("click", function () {});
